data_maol=read.csv2('C:/Users/ASUS/Downloads/DirectMarketing.csv')
plot(data_maol$AmountSpent, data_maol$Salary)
data_maol=read.csv2("C:/Users/ASUS/Downloads/DirectMarketing.csv") 
hist(data_maol$AmountSpent) maol=density(data_maol$AmountSpent) 
maol=read.csv("C:/Users/ASUS/Downloads/DirectMarketing.csv")
hist(maol$AmountSpent)
data_maol=read.csv2("C:/Users/ASUS/Downloads/DirectMarketing.csv")
hist(data_maol$AmountSpent)
dz=density(data_maol$AmountSpent)
maol=density(data_maol$AmountSpent)
plot(maol)
plot(dz)
maol=read.csv("C:/Users/ASUS/Downloads/houseprice.csv")
plot(maol$Price, maol$aqFT)
